name: Deploy with Terragrunt

description: "Despliega la infraestructura usando Terragrunt en el entorno seleccionado (dev o prd)"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selecciona el entorno a desplegar'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prd

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set GCP Project
        id: set_project
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "PROJECT_ID=agro-extension-digital-npe" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "prd" ]]; then
            echo "PROJECT_ID=agro-extension-digital-prd" >> $GITHUB_ENV
          else
            echo "Entorno no soportado: ${{ github.event.inputs.environment }}"
            exit 1
          fi

      - name: Authenticate to Google Cloud
        run: |
          echo "$GCP_SA_KEY" > /tmp/account.json
          gcloud auth activate-service-account --key-file=/tmp/account.json
          gcloud config set project $PROJECT_ID

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     terraform_version: 1.7.5

      # - name: Set up Terragrunt
      #   run: |
      #     wget -O terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.59.1/terragrunt_linux_amd64
      #     chmod +x terragrunt
      #     sudo mv terragrunt /usr/local/bin/

      - name: Deploy with Terragrunt
        working-directory: cicd/${{ github.event.inputs.environment }}
        run: |
          terragrunt init
          terragrunt apply -auto-approve
